config/routes.rb
Rails.application.routes.draw do
  root "books#top"
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates :title,  presence: true
 validates :body,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      render :index
      @book = Book.new(book_params)
    end
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :edit
      @book = Book.find(params[:id])
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    if book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, local:true do |f| %>
<% if @book.errors.any? %>
<h3><%= @book.errors.count %> error prohibited this book from being saved:</h3>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<label>title</label>
<%= f.text_field :title %>
<label>body</label>
<%= f.text_area :body %>
<%= f. submit "Update Book" %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<p><%= flash[:notice] %></p>
<h1>Books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
  <tr>
 <% @books.each do |f| %>
      <td><%= f.title %></td>
      <td><%= f.body %></td>
      <td><%= link_to "Show", book_path(f.id) %></td>
    <td><%= link_to "edit", edit_book_path(f.id) %></td>
    <td><%= link_to "Destroy", book_path(f.id), method: :delete %></td>
 </tr>
  <% end %>
</table>

<h1>New book</h1>
<%= form_with model:@book, local:true do |f| %>
<% if @book.errors.any? %>
<h3><%= @book.errors.count %> error prohibited this book from being saved:</h3>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<label>title</label>
  <%= f.text_field :title %>
<label>body</label>
  <%= f.text_area :body %>
<%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<p><%= flash[:notice] %></p>
<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ！</h1>
  <p>Bookers では、さまざまな書籍に関するあなたの意見や
  印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebcampTask2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>